/**
 * Interactive setup wizard. Generates a .env tailored to the operator, then
 * optionally runs migrations and mints a first admin API key.
 *
 *   npm run setup
 *
 * Pure Node — no extra dependencies. Safe to re-run (it asks before overwriting
 * an existing .env).
 */
import { createInterface } from "node:readline";
import { stdin as input, stdout as output } from "node:process";
import { writeFile, readFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";

// A line reader that buffers input lines arriving before they're requested.
// This works both interactively (a human typing) and with piped/redirected
// input (scripted installs), avoiding readline's bulk-input race.
const rl = createInterface({ input, output });
const pending: string[] = [];
const waiters: Array<(line: string) => void> = [];
rl.on("line", (line) => {
  const w = waiters.shift();
  if (w) w(line);
  else pending.push(line);
});

function nextLine(): Promise<string> {
  const buffered = pending.shift();
  if (buffered !== undefined) return Promise.resolve(buffered);
  return new Promise((resolve) => waiters.push(resolve));
}

async function ask(question: string, def?: string): Promise<string> {
  const suffix = def !== undefined ? ` [${def}]` : "";
  output.write(`${question}${suffix}: `);
  const answer = (await nextLine()).trim();
  return answer || def || "";
}

async function askYesNo(question: string, def = false): Promise<boolean> {
  const ans = (await ask(`${question} (${def ? "Y/n" : "y/N"})`)).toLowerCase();
  if (!ans) return def;
  return ans === "y" || ans === "yes";
}

function fileExists(path: string): Promise<boolean> {
  return readFile(path).then(
    () => true,
    () => false,
  );
}

async function main() {
  console.log("\n  Yup CMS — setup\n  ===============\n");

  if (await fileExists(".env")) {
    const overwrite = await askYesNo(".env already exists. Overwrite it?", false);
    if (!overwrite) {
      console.log("Keeping existing .env. Nothing changed.");
      rl.close();
      return;
    }
  }

  console.log("Database (Postgres). Defaults match docker-compose.yml.\n");
  const dbName = await ask("  Database name", "yup");
  const dbUser = await ask("  Database user", "yup");
  const dbPass = await ask(
    "  Database password",
    randomBytes(12).toString("hex"),
  );
  const dbHostPort = await ask(
    "  Host:port for tools running outside Docker",
    "localhost:5432",
  );

  console.log("\nContent & API\n");
  const authorType = await ask(
    "  Default author type for writes (agent/human/system)",
    "agent",
  );
  const authorId = await ask("  Default author id", "yup-agent");
  const apiPort = await ask("  Read API port", "3000");
  const lockReads = await askYesNo(
    "  Require an API key for ALL reads (else only non-published)?",
    false,
  );

  const hostUrl = `postgres://${dbUser}:${dbPass}@${dbHostPort}/${dbName}`;

  const env = `# Generated by \`npm run setup\`

# --- Database ---
POSTGRES_USER=${dbUser}
POSTGRES_PASSWORD=${dbPass}
POSTGRES_DB=${dbName}

# Used by tools run on the host (npm run api/seed/migrate).
# Inside docker-compose the API container overrides this to point at host "db".
DATABASE_URL=${hostUrl}

# --- Content defaults (author attribution) ---
CMS_DEFAULT_AUTHOR_TYPE=${authorType}
CMS_DEFAULT_AUTHOR_ID=${authorId}

# --- Read API ---
CMS_API_PORT=${apiPort}
CMS_REQUIRE_API_KEY=${lockReads}
`;

  await writeFile(".env", env, "utf8");
  console.log("\n✓ Wrote .env\n");

  // Optional: run migrations + mint an admin key, if the DB is reachable now.
  const initNow = await askYesNo(
    "Is the database already running and reachable now? Run migrations + create an admin key?",
    false,
  );

  if (initNow) {
    process.env.DATABASE_URL = hostUrl;
    try {
      console.log("\n→ Running migrations...");
      const { drizzle } = await import("drizzle-orm/postgres-js");
      const { migrate } = await import("drizzle-orm/postgres-js/migrator");
      const postgres = (await import("postgres")).default;
      const sql = postgres(hostUrl, { max: 1 });
      await migrate(drizzle(sql), { migrationsFolder: "./drizzle" });
      await sql.end();
      console.log("✓ Migrations applied.");

      console.log("\n→ Creating admin API key...");
      const { createApiKey } = await import("../core/auth.js");
      const result = await createApiKey({ name: "admin", scopes: ["admin"] });
      console.log("\n  Your admin API key (shown once — store it now):\n");
      console.log(`    ${result.key}\n`);
    } catch (err) {
      console.error(`\n⚠ Could not initialize: ${(err as Error).message}`);
      console.error("  Start the database, then run: npm run db:migrate");
    }
  } else {
    console.log("\nNext steps:");
    console.log("  docker compose up -d      # starts Postgres + API (+ migrations)");
    console.log("  # or, running on the host:");
    console.log("  npm run db:migrate        # create the schema");
    console.log("  npm run api               # start the read API");
  }

  console.log("\nDone.\n");
  rl.close();
}

main().catch((err) => {
  console.error(err);
  rl.close();
  process.exit(1);
});
